server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@172.16.131.75:3306/bitrade?characterEncoding=utf-8
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 0.1s
    read_timeout: 0.2s
    write_timeout: 0.2s
